### ISSUE TITLE
CF password policy breaks 'meow'

### ISSUE THREAD

**Issue by Callisto13** [cloudfoundry-incubator/cf-test-helpers#15]
Hi,
From CF v213 onwards there is an [optional password policy](https://github.com/cloudfoundry/cf-release/blob/master/jobs/uaa/spec) - would it be possible to change the regularUserPassword to something more elaborate so that tests don't fail for users who have set policies? (I know, it's an awful shame to lose meow).

I was going to to do this via pull request, but as meow is only mentioned in 4 places it didn't seem worth it for everyone to have to deal with the go import run-around!
Thanks!

**Comment by jeffpak93** [comment]
Hi @Callisto13 ,

We were thinking that instead of changing the regularUserPassword, it would be better to make this configurable for users. Currently we don't have any plans to implement such a feature, but if you'd like to submit another PR that perhaps parses the configuration to accept the password, we could take another look into this. 

Best,
@jeffpak93 & @jberkhahn, CFCAPI

**Comment by Callisto13** [comment]
Okay,
Have submitted https://github.com/cloudfoundry-incubator/cf-test-helpers/pull/16
